### ISSUE TITLE
GEM Authentication Error

### ISSUE THREAD

**Issue by vilusa** [SignRequest/signrequest-ruby-client#5]
Hi everyone,

I'am using the official gem, configure gem for my credentials but receiving `"{\"detail\":\"Authentication credentials were not provided.\"}"`

Intializers File
```ruby
SignRequestClient.configure do |config|
  # Configure API key authorization: Token
  config.api_key['Authorization'] = "my_api_key"
  # Uncomment the following line to set a prefix for the API key, e.g. 'Bearer' (defaults to nil)
  config.api_key_prefix['Authorization'] = 'Bearer'
end
```

Error Screenshot
![Screen Shot 2021-02-23 at 4 50 14 PM](https://user-images.githubusercontent.com/8127141/108852975-416d8300-75f7-11eb-9ba3-f9a4a470f9a2.png)

**Comment by LPascholatti** [comment]
Hi, have you added the word 'Token' before the actual token, for example "Token xxxxxx-xxxxx-xxxx-xxxxx"? 

If you still need help, please reach out to me via SignRequest's tech support so we can debug it via logs support@signrequest.com

**Comment by vilusa** [comment]
Hi, @LPascholatti  thanks for your answer.

Solved authentication problem now I'm receiving `"{\"signers\":[\"This field is required.\"]}"` for quick create sign request

My request payload
```json
redirect_url_declined: ...,
signers: [
  {
     "email": "email",
     "first_name": "Kemal",
     "last_name": "AKIN"
  }
],
prefill_tags: ....
```

**Comment by LPascholatti** [comment]
Hi, good to know you managed with the authentication. The e-mail field is mandatory. It should be an actual address and it should not coincide with your from_email address

**Comment by vilusa** [comment]
Hi, email address is valid and different from_email

**Comment by LPascholatti** [comment]
I'd suggest you get in touch with SignRequest via our support channels, so we can discuss your log details. Your e-mail address/subdomain should be enough to debug it. That shouldn't be an issue with the Ruby gem.

**Comment by vilusa** [comment]
So thanks @LPascholatti
